---
- hosts: ansible
  become: true
  tasks:
  - name: Install epel release package for extra pacakages
    yum:
     name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
     state: present
     disable_gpg_check: true
  
  - name: Install vim, java & ansible packages
    yum:
     name: ['vim', 'python3', 'java-11-openjdk-devel']
     state: present
  
  - name: Set the alternatives for python3
    shell:
       alternatives --set python /usr/bin/python3
  
  - name: Install the ansible package
    yum:
     name: ansible
     state: present
  
  - name: Create the ansible user
    user:
      name: ansible
      create_home: yes
      shell: /bin/bash
      password: "{{ 'redhat' | password_hash('sha512','A512') }}"
  
  - name: sudo access for ansible user
    copy:
     dest: /etc/sudoers.d/ansible
     content: 'ansible ALL=(ALL) NOPASSWD: ALL' 
     validate: /usr/sbin/visudo -cf %s
  
  - name: copy file
    copy:
      src: filinta.pem  
      dest: /home/ansible/

  - name: Append text to file
    blockinfile:
      path: /etc/ansible/hosts
      block: |
        #IP ansible_user=ec2-user ansible_ssh_private_key_file=/home/ansible/filinta.pem

  - name: enable password authentication
    lineinfile:
     dest: /etc/ssh/sshd_config
     regexp: "^PasswordAuthentication"
     line: "PasswordAuthentication yes"
     state: present
    notify: Restart sshd
  handlers:
  
  - name: Restart sshd
    service:
     name: sshd
     service: restarted  
...
